import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "rVVeLdouViU",
    video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "JSZmQxg3fos",
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "10:12",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "ufRtWGd0cXo",
    video_title:
      "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
    video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "ufRtWGd0cXo",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:18",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "7OuSRaIPOds",
    video_title:
      "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
    video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
    tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
    cover_image: "7OuSRaIPOds",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:13",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "F-1DqS0iQ0s",
    video_title: "Facade Process",
    video_description: `Discover how modern building facades are engineered and installed with precision, transforming architectural concepts into high-performance exteriors.`,
    tags: ["Modern building facades", "Facade Installation"],
    cover_image: "F-1DqS0iQ0s",
    publish_date: "2026-04-16",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/F-1DqS0iQ0s?si=z2ofxSuaN7VKCJsI",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:16",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "CoL99xlmBHg",
    video_title: "ACP Transformation",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["ACP", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "CoL99xlmBHg",
    publish_date: "2026-05-19",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CoL99xlmBHg?si=pVG6T98Sr0JpBgZX",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:17",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "oKp6CHbP2sE",
    video_title: "Premium pergola solutions that transform terraces, rooftops, resorts,villas",
    video_description:
      "Premium pergola solutions by HG Walls, crafted to elevate terraces, villas, cafés, resorts, and commercial spaces with modern design.",
    tags: ["Premium pergola", "terraces", "rooftops", "resorts"],
    cover_image: "oKp6CHbP2sE",
    publish_date: "2026-06-13",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/oKp6CHbP2sE?si=vViXGGooXSWHln6r",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:22",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "0wGDE0a5Dyw",
    video_title: " Complete Facade Installation Process | From Design to Installation",
    video_description:
      "A complete overview of HG Walls' facade installation process, showcasing precision engineering, quality craftsmanship, and modern exterior solutions.",
    tags: ["Facade Installation", "Structural Glazing", "Project Showcase", "Architecture"],
    cover_image: "0wGDE0a5Dyw",
    publish_date: "2026-06-29",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/0wGDE0a5Dyw?si=V6kRbkJWMJrUHOiU",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:18",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "-kkknSOdgwo",
    video_title: "पुण्य के नाम पर पाप? | आस्था के नाम पर प्रदूषण",
    video_description:
      "यह वीडियो बताता है कि सच्ची आस्था प्रकृति की रक्षा में है, न कि नदियों को प्रदूषित करने वाली परंपराओं में।",
    tags: ["सामाजिक जागरूकता", "पर्यावरण जागरूकता", "धार्मिक जागरूकता", "शैक्षणिक शॉर्ट्स"],
    cover_image: "-kkknSOdgwo",
    publish_date: "2026-03-26",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-kkknSOdgwo?si=l8HCRjkNf942lEye",
    project_images: [],
    category: ["Shorts"],
    duration: "0:41",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "OaN7iV8zvUY",
    video_title: "शिक्षित होना, धार्मिक होने से ज़्यादा ज़रूरी है",
    video_description:
      "यह वीडियो होली के दौरान सम्मान, जिम्मेदारी और सामाजिक जागरूकता का संदेश देता है, बताते हुए कि परंपरा कभी भी बदसलूकी का समर्थन नहीं करती।",
    tags: ["सामाजिक जागरूकता", "शैक्षणिक शॉर्ट्स", "त्योहार जागरूकता", "जन-जागरूकता"],
    cover_image: "OaN7iV8zvUY",
    publish_date: "2026-03-31",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/OaN7iV8zvUY?si=q9GE0PpnUQoHpwgw",
    project_images: [],
    category: ["Shorts"],
    duration: "0:33",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "cSNlAjq5mv4",
    video_title: "Travel with purpose",
    video_description:
      "Ghoomantu is a travel community that promotes sustainable travel, offbeat destinations, and authentic group adventures across India.",
    tags: ["Educational Shorts",
      "Travel Guide",
      "Social Awareness",
      "Storyteling"],
    cover_image: "cSNlAjq5mv4",
    publish_date: "2026-03-07",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/cSNlAjq5mv4?si=V56JDTgGC6FBeKM6",
    project_images: [],
    category: ["Shorts"],
    duration: "1:49",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "XM0DTazadzc",
    video_title: "पहाड़ों में पार्टी और SHOR SHARABA? 🤬 | बंद करो ये तमाशा",
    video_description: "यह वीडियो सम्मानजनक और जिम्मेदार यात्रा के महत्व को उजागर करता है, साथ ही यात्रियों को प्रकृति और स्थानीय संस्कृति का सम्मान करने के लिए प्रेरित करता है।",
    tags: [
      "Educational Shorts",
      "Travel Guide",
      "Social Awareness",
      "Storyteling",
    ],
    cover_image: "XM0DTazadzc",
    publish_date: "2026-04-01",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/XM0DTazadzc?si=c3JWXdMV0OW6qqyq",
    project_images: [],
    category: ["Shorts"],
    duration: "0:58",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "-UqbDmhtqM0",
    video_title:
      "Traveller Bano, Tourist Nahi | Don't Come to Mountains for Comfort",
    video_description: `Mountains are meant to be experienced, not exploited. Responsible travel is about respecting nature, supporting local communities, and preserving the Himalayas.`,
    tags: ["Educational Shorts", "Travel Guide", "Social Awareness", "Storyteling"],
    cover_image: "-UqbDmhtqM0",
    publish_date: "2026-03-25",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-UqbDmhtqM0?si=nhkBcAkMOiydyrUR",
    project_images: [],
    category: ["Shorts"],
    duration: "0:44",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "PN7WwBWRsq8",
    video_title: "आस्था या अंधविश्वास? प्रकृति को नुकसान पहुँचाना धर्म नहीं",
    video_description:
      "गंगा और अन्य नदियों में दूध, घी या पूजा सामग्री डालने से जल प्रदूषण बढ़ता है और जलीय जीवों के लिए ऑक्सीजन की कमी पैदा हो सकती है।",
    tags: ["Environment", "Sustainability", "Green Revolution", "Storyteling"],
    cover_image: "PN7WwBWRsq8",
    publish_date: "2026-03-28",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/PN7WwBWRsq8?si=IoAqrgb8M3-wNgbv",
    project_images: [],
    category: ["Shorts","Motion Graphics"],
    duration: "1:05",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "LhgYRv1CTGw",
    video_title: "Why Michael Jackson Couldn’t Be Saved",
    video_description: `Michael Jackson's final days were shaped by decades of physical pain, personal struggles, and industry pressure that ultimately led to one of music's most tragic losses`,
    tags: [
      "Michael Jackson Death",
      "Biography Documentary",
      "Investigative Documentary",
      "Explainer Video",
    ],
    cover_image: "LhgYRv1CTGw",
    publish_date: "2026-06-19",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/LhgYRv1CTGw?si=my0FNce4SBj1SduT",
    project_images: [],
    category: ["Documentary"],
    duration: "9:29",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "d_ig9TouhM8",
    video_title: "Why Justin Bieber Sucks Now",
    video_description: `A deep-dive documentary exploring Justin Bieber's career, media narrative, and the complex relationship between fame, branding, and public perception.`,
    tags: ["Justin Bieber", "Pop Culture", "Music Industry", "Biography"],
    cover_image: "d_ig9TouhM8",
    publish_date: "2026-04-08",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/d_ig9TouhM8?si=jbTAUtzTkbdf2lMR",
    project_images: [],
    category: ["Documentary"],
    duration: "9:00",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "0cpURR_Anow",
    video_title: "Ellen DeGeneres Playing the Victim After Getting Exposed",
    video_description:
      "Behind Ellen DeGeneres' successful career lies a story of workplace scandals, public criticism, and a comeback that divided audiences.",
    tags: [
      "Ellen DeGeneres",
      "Celebrity Documentary",
      "Investigative Documentary"],
    cover_image: "0cpURR_Anow",
    publish_date: "2026-02-20",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/0cpURR_Anow?si=wjV91bHF2cR-Xbnb",
    project_images: [],
    category: ["Documentary"],
    duration: "13:25",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "SA82SI6RBnU",
    video_title: "The DARK Side of Logan Paul’s Pokémon Strategy",
    video_description: `A documentary-style investigation exploring Logan Paul's Pokémon investments, exposing the psychology, risks, and strategies behind celebrity-driven hype.`,
    tags: ["Logan Paul","Investigative Documentary",
      "Pokémon Cards"],
    cover_image: "SA82SI6RBnU",
    publish_date: "2026-07-24",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/SA82SI6RBnU?si=36wqazLujkzp0V12",
    project_images: [],
    category: ["Documentary"],
    duration: "19:59",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "FZmyZXQI0MY",
    video_title: "This Is Why Jennifer Lawrence Is So Different",
    video_description: `Behind the fame lies a rare authenticity—this documentary explores how Jennifer Lawrence redefined modern celebrity culture.`,
    tags: [
      "Jennifer Lawrence",
      "Documentary Editing",
      "Celebrity Documentary"    ],
    cover_image: "FZmyZXQI0MY",
    publish_date: "2026-07-15",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/FZmyZXQI0MY?si=XVyGo1P-y92Xlsr8",
    project_images: [],
    category: ["Documentary"],
    duration: "9:45",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "hjtohuZYNsY",
    video_title: "The Ronaldo Nobody Knows | Tax Fraud, NDAs & Al-Nassr",
    video_description: `Beyond the records and trophies lies the story of Cristiano Ronaldo's fame, controversies, and the carefully crafted image that shaped his legacy.`,
    tags: [
      "Cristiano Ronaldo",
      "Documentary Editing",
      "Celebrity Documentary",
    ],
    cover_image: "hjtohuZYNsY",
    publish_date: "2026 -08-01",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/M9znCGjupcY",
    project_images: [],
    category: ["Documentary"],
    duration: "8:33",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "-iqghJvuGgk",
    video_title:
      "The Man Who Destroyed Michael Jackson",
    video_description: `Michael Jackson became the King of Pop—but behind the fame was a childhood shaped by fear, abuse, and his father's relentless pressure.`,
    tags: ["Michael Jackson Documentary", "Documentary Editing", "Storytelling"],
    cover_image: "-iqghJvuGgk",
    publish_date: "2026-05-18",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/-iqghJvuGgk?si=DRtFTG5UwrwtihKt",
    project_images: [],
    category: ["Documentary"],
    duration: "11:11",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
];
